import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#F7F7FB",
  },
  keyboardContainer: {
    flex: 1,
  },
  page: {
    flexGrow: 1,
    paddingHorizontal: 22,
    paddingTop: 22,
    paddingBottom: 24,
  },
  widePage: {
    flexDirection: "row",
    padding: 0,
    minHeight: "100%",
  },
  mobileBrand: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 42,
  },
  brandMark: {
    width: 40,
    height: 40,
    borderRadius: 13,
    backgroundColor: "#6B2EEF",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 11,
  },
  brandMarkText: {
    color: "#FFFFFF",
    fontSize: 23,
    fontWeight: "800",
    letterSpacing: -1,
  },
  brandName: {
    color: "#242238",
    fontSize: 21,
    fontWeight: "800",
    letterSpacing: -0.6,
  },
  formPanel: {
    flex: 1,
    width: "100%",
    maxWidth: 520,
    alignSelf: "center",
    justifyContent: "center",
  },
  wideFormPanel: {
    maxWidth: 590,
    paddingHorizontal: 64,
    paddingVertical: 50,
  },
  formContent: {
    width: "100%",
  },
  headingBlock: {
    marginBottom: 30,
  },
  eyebrow: {
    color: "#6B2EEF",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1.6,
    marginBottom: 10,
  },
  title: {
    color: "#242238",
    fontSize: 30,
    lineHeight: 37,
    fontWeight: "800",
    letterSpacing: -0.8,
    marginBottom: 9,
  },
  subtitle: {
    color: "#77768A",
    fontSize: 14,
    lineHeight: 21,
  },
  roleBlock: {
    marginBottom: 23,
  },
  fieldLabel: {
    color: "#302E43",
    fontSize: 13,
    fontWeight: "700",
    marginBottom: 9,
  },
  roleSelector: {
    position: "relative",
    height: 50,
    borderRadius: 14,
    padding: 4,
    backgroundColor: "#F0EEF6",
    flexDirection: "row",
    overflow: "hidden",
  },
  roleOption: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 11,
  },
  selectedRoleOption: {
    backgroundColor: "#6B2EEF",
    shadowColor: "#6B2EEF",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 3,
  },
  roleOptionText: {
    color: "#767487",
    fontSize: 13,
    fontWeight: "700",
  },
  selectedRoleText: {
    color: "#FFFFFF",
  },
  roleHint: {
    color: "#89889A",
    fontSize: 12,
    marginTop: 8,
  },
  inputGroup: {
    marginBottom: 19,
  },
  textInput: {
    height: 52,
    borderWidth: 1,
    borderColor: "#E5E3ED",
    borderRadius: 13,
    paddingHorizontal: 15,
    backgroundColor: "#FFFFFF",
    color: "#242238",
    fontSize: 14,
  },
  ownerAccountList: {
    marginBottom: 19,
  },
  ownerAccountOption: {
    padding: 14,
    marginBottom: 9,
    borderWidth: 1,
    borderColor: "#E5E3ED",
    borderRadius: 13,
    backgroundColor: "#FFFFFF",
  },
  selectedOwnerAccountOption: {
    borderColor: "#6B2EEF",
    backgroundColor: "#F5F1FF",
  },
  ownerAccountName: {
    color: "#302E43",
    fontSize: 14,
    fontWeight: "700",
  },
  ownerAccountUsername: {
    color: "#77768A",
    fontSize: 12,
    marginTop: 4,
  },
  formOptions: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 1,
    marginBottom: 25,
  },
  rememberOption: {
    flexDirection: "row",
    alignItems: "center",
    marginLeft: -8,
  },
  rememberText: {
    color: "#626174",
    fontSize: 12,
    fontWeight: "500",
    marginLeft: 3,
  },
  forgotPassword: {
    color: "#6B2EEF",
    fontSize: 12,
    fontWeight: "700",
  },
  loginButton: {
    height: 54,
    borderRadius: 14,
    backgroundColor: "#6B2EEF",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#6B2EEF",
    shadowOffset: { width: 0, height: 7 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 4,
  },
  loginButtonPressed: {
    opacity: 0.88,
    transform: [{ scale: 0.99 }],
  },
  loginButtonDisabled: {
    opacity: 0.5,
  },
  loginButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "700",
  },
  loginButtonArrow: {
    color: "#FFFFFF",
    fontSize: 20,
    fontWeight: "500",
    marginLeft: 10,
    marginTop: -2,
  },
  signupPrompt: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 23,
  },
  signupText: {
    color: "#77768A",
    fontSize: 12,
  },
  signupLink: {
    color: "#6B2EEF",
    fontSize: 12,
    fontWeight: "700",
  },
  footerText: {
    color: "#A3A2B0",
    fontSize: 10,
    textAlign: "center",
    marginTop: 35,
  },
  heroPanel: {
    flex: 1,
    minHeight: 700,
    paddingHorizontal: 56,
    paddingTop: 50,
    paddingBottom: 44,
    backgroundColor: "#6B2EEF",
    justifyContent: "space-between",
    overflow: "hidden",
  },
  heroBrand: {
    flexDirection: "row",
    alignItems: "center",
    zIndex: 1,
  },
  heroBrandMark: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  heroBrandMarkText: {
    color: "#6B2EEF",
    fontSize: 24,
    fontWeight: "800",
  },
  heroBrandName: {
    color: "#FFFFFF",
    fontSize: 22,
    fontWeight: "800",
    letterSpacing: -0.5,
  },
  heroCopy: {
    maxWidth: 470,
    marginTop: 70,
    marginBottom: 60,
    zIndex: 1,
  },
  heroEyebrow: {
    color: "#DDD0FF",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1.6,
    marginBottom: 18,
  },
  heroTitle: {
    color: "#FFFFFF",
    fontSize: 48,
    lineHeight: 56,
    fontWeight: "800",
    letterSpacing: -1.5,
    marginBottom: 19,
  },
  heroSubtitle: {
    maxWidth: 390,
    color: "#E7DEFF",
    fontSize: 15,
    lineHeight: 24,
  },
  heroCard: {
    minHeight: 84,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 18,
    borderRadius: 17,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.25)",
    backgroundColor: "rgba(255,255,255,0.12)",
    zIndex: 1,
  },
  heroCardIcon: {
    width: 40,
    height: 40,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFFFF",
    marginRight: 13,
  },
  heroCardIconText: {
    color: "#6B2EEF",
    fontSize: 20,
    fontWeight: "800",
  },
  heroCardCopy: {
    flex: 1,
  },
  heroCardTitle: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "700",
    marginBottom: 5,
  },
  heroCardSubtitle: {
    color: "#E7DEFF",
    fontSize: 11,
  },
  heroCardDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#B7FFDA",
    marginLeft: 10,
  },
  heroDecoration: {
    position: "absolute",
    width: 340,
    height: 340,
    borderRadius: 170,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
    top: "27%",
    right: -170,
  },
  heroDecorationSmall: {
    position: "absolute",
    width: 220,
    height: 220,
    borderRadius: 110,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.10)",
    top: "37%",
    right: -110,
  },
});
